### ISSUE TITLE
Zemljevidi

### ISSUE THREAD

**Issue by jaanos** [SamoFMF/APPR-2014-15#5]
Ko poženem program, se mi ustavi, ko poskušaš izpisati imena na drugi zemljevid. Problem je v tem, da imaš manjkajoče podatke pri koordinatah v razpredelnici `imena`.

Problem se pojavi pri preimenovanju vrstic, saj želeni vrstici pri uvozu nista na navedenih mestih. Namesto tega raje naredi

``` R
row.names(drzave)[row.names(drzave) == "Serbia"] <- "Republic of Serbia"
row.names(drzave)[row.names(drzave) == "United States"] <- "United States of America"
```

Naslednjo vrstico lahko enostavneje zapišeš kot

``` R
drzave <- drzave[row.names(drzave) %in% svet$admin,]
```

Podobno naredi seveda tudi z razpredelnico `povrsina`. Pri uvozu bi se spodobilo podati še kodiranje znakov `"Windows-1252"`, da bo pravilno uvozilo imena, kot npr. `"Côte d'Ivoire"`.

Pri prvem zemljevidu daj celoten ukaz `spplot` kot argument ukazu `print`, torej

``` R
print(spplot(svet, "stevilo.trgovin", col.regions = rainbow(16)))
```

sicer ti pri poganjanju programa ne bo izrisalo zemljevida (iz konzole deluje tudi brez `print`).

Obema zemljevidoma dodaj še naslov (pri `spplot` s parametrom `main`, pri `plot` pa z ukazom `title`) ter poskrbi, da bosta čitljiva - pri drugem lahko tako nekoliko prirediš koordinate, da imena držav ne bodo segala čez meje. Lahko prirediš tudi izpisana imena (npr. namesto `"Saudi Arabia"` izpišeš `"Saudi\nArabia"`, da bo naredilo prelom vrstice); s parametrom `srt` pa lahko zarotiraš imena. Žal ta ne sprejema vektorjev vrednosti, tako da če bi želel zarotirati npr. oznako `"Argentina"`, bi jo moral izpustiti pri izpisovanju vseh držav, potem pa jo izpisati z novim ukazom `text` s parametrom `srt = 90`.

Še ena malenkost v poročilu: takoj na začetku seže beseda `razširjenost` čez rob. LaTeX ima včasih težave z deljenjem besed s šumniki, tako da mu lahko namigneš, kje lahko deli besedo:

``` LaTeX
raz\-ši\-rje\-nost
```

Pri imenih datotek v `\verb` to ne bo delovalo - lahko sicer poskusiš nekoliko drugače napisati, da imena ne bodo štrlela, a je to bolj obrobnega pomena.

**Comment by SamoFMF** [comment]
Sem popravil vse zgoraj naštete napake. Sicer je meni že prej izrisalo drug zemljevid, kot mi ga tudi sedaj.

Sem upošteval tudi predloge za imena/kratice/oznake na zemljevidu, tako da so sedaj znotraj mej držav, v latexu pa sem rahlo preoblikoval tekst, tako da je sedaj vse znotraj robov.

**Comment by SamoFMF** [comment]
Prosim preverite še, če nimate zemljevida, ki sem ga imel nekaj dni nazaj, ki je vseboval samo 181 držav. Le-tega sem kasneje zamenjal za malce boljšega, ki jih vsebuje 241, kar bi lahko povzročilo, da se imena niso ujemala v vaši verziji.

Trenutno se uporablja http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_countries.zip

**Comment by jaanos** [comment]
Funkcija `uvozi.zemljevid`, preveri, če je na želenem mestu navedena datoteka s končnico `.shp` - če je, jo uporabi, v nasprotnem primeru pa pobere zemljevid z navedenega spletnega naslova. Tako sem zagotovo pridobil pravi zemljevid, glede na to, da imaš navedeno pravo ime datoteke.

Še eno malenkost sem opazil: pri tretjem grafu sam rišeš osi, zato so osnovne osi grafa nepotrebne. Znebiš se jih tako, da ukazu `plot` podaš parameter `axes = FALSE`.

**Comment by SamoFMF** [comment]
Sem mislis, če ste slučajno si že naložili starejši program, ter imeli staro .SHP datoteko shranjeno. No mislim, da bi sedaj moralo vse delovati, kot je treba.

Hvala, sem popravil.
